#!/usr/bin/env bash
#
#------------------------------------------------------------------------------
# Install
# Copyright (C) 2024  Jacob Kochems <jacobkochems+git@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#------------------------------------------------------------------------------
#
# Install symlink pointing at 'tracelink' script into ~/.local/bin/
#

set -e -o pipefail

ln -sf "$(realpath .)"/tracelink "$HOME"/.local/bin/tracelink 
