#!/usr/bin/env bash
#
#------------------------------------------------------------------------------
# Tracelink
# Copyright (C) 2023  Jacob Kochems
# SPDX-License-Identifier: GPL-3.0-or-later
#------------------------------------------------------------------------------
#
# Trace symbolic links all the way back to the regular file and
# print out all intermediate symlinks.
#

this=$(basename "$0")

if [[ $# == 0 ]]; then
    echo "Usage: $(basename "$0") SYMLINK_1 [SYMLINK_2 ...]"
    exit 1
fi

function panic {
   echo "$this:" "$@"
   exit 1
}

function get_full_path {
    realpath --canonicalize-existing --no-symlinks "$@"
}

for symlink in "$@"
do
    # proceed to current symlink and print out its canonical form
    next="$symlink"
    get_full_path "$next" || panic "$next:" no such file

    # iterate from link to link until the chain ends at a regular file
    while lnk=$(readlink "$next"); do
        if [[ $lnk == /* ]]; then
            # case: absolute path
            next=$lnk
        else
            # case: relative path
            next=$(dirname "$next")/"$lnk"
        fi
        # print out current step
        get_full_path "$next" || panic "$next": no such file
    done
    echo
done
