#!/usr/bin/env bash
#
#------------------------------------------------------------------------------
# Tracelink
# Copyright (C) 2023  Jacob Kochems
# SPDX-License-Identifier: GPL-3.0-or-later
#------------------------------------------------------------------------------
#
# Trace symbolic links all the way back to the regular file and
# print out all intermediate symlinks.
#

if [[ $# == 0 ]]; then
    echo "Usage: $(basename "$0") SYMLINK_1 [SYMLINK_2 ...]"
    exit 1
fi

for symlink in "$@"
do
    # proceed to current symlink and print it out
    next="$symlink"
    realpath -s "$next"
    # iterate from link to link until the chain ends at a regular file
    while lnk=$(readlink "$next"); do
        # proceede to next link in the chain and print it out
        next=$lnk
        realpath -s "$next"
    done
    echo
done
